### ISSUE TITLE
Segfault on shutdown

### ISSUE THREAD

**Issue by gebn** [gebn/bmc_exporter#6]
```
2019/08/21 15:45:17 waiting for in-progress requests to finish...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x83597e]

goroutine 75 [running]:
github.com/gebn/bmc_exporter/collector.(*Collector).Close(0xc0001e8280, 0xb22920, 0xc0001880c0, 0x0, 0x0)
        external/com_github_gebn_bmc_exporter/collector/collector.go:155 +0x7e
github.com/gebn/bmc_exporter/handler/bmc.(*Mapper).Close.func1(0xc000036150, 0xb228e0, 0xc0000360c0, 0xc000190020)
        external/com_github_gebn_bmc_exporter/handler/bmc/mapper.go:188 +0x98
created by github.com/gebn/bmc_exporter/handler/bmc.(*Mapper).Close
        external/com_github_gebn_bmc_exporter/handler/bmc/mapper.go:184 +0x17b
```

**Comment by gebn** [comment]
Happens when a collector is `Close()`d  that has not initialised successfully. To fix alongside #18.
